### ISSUE TITLE
MiniZinc dependency version

### ISSUE THREAD

**Issue by SebAlbert** [CP-Unibo/sunny-cp#2]
I just read in the README (section on Manual Installation)

> MiniZinc (version >= 2.7.1)

As far as I can see, the current version of MiniZinc is only 2.2.3. Can you clarify?

**Comment by ramadini** [comment]
You are right, that was a typo. The actual version is 2.1.7 (see this commit: https://github.com/CP-Unibo/sunny-cp/commit/81dae9df4eddc6025b9844320261690a63252730#diff-04c6e90faac2675aa89e2176d2eec7d8)

I fixed the typo.

Roberto.
